language: minimal
after_success:
  - git config --global user.email "build@travis-ci.com"
  - git config --global user.name "Travis CI"
  - GIT_TAG=$(cat requirements.txt)
  - export GIT_TAG=${GIT_TAG#awscli==}
  - git tag "$GIT_TAG" -a -m "Tag for AWS CLI v$GIT_TAG"
  - <<<$SSH_KEY_PEM_BASE64 base64 -d > ~/.ssh/id_rsa
  - chmod 400  ~/.ssh/id_rsa
  - git push ssh://git@github.com/sgreben/docker-aws-cli-with-assumed-role.git "$GIT_TAG"
branches:
  only:
  - master
